Instrucciones 
 
1. Carga y estructuración de datos: 
○ Crea un array NumPy con datos financieros simulados (por ejemplo, 
precios de acciones en diferentes días). 
○ Organiza los datos en una matriz de 5x5, donde cada fila representa 
una acción y cada columna un día de cotización. 
2. Análisis y transformación de datos: 
○ Obtén el promedio, valor máximo y mínimo de cada acción a lo 
largo del tiempo. 
○ Calcula la variación porcentual diaria de cada acción. 
○ Aplica funciones matemáticas como logaritmo, exponencial o 
normalización sobre los datos. 
3. Optimización y selección de datos: 
○ Utiliza indexación avanzada para extraer información específica, 
como el rendimiento de una acción en un día determinado. 
○ Aplica broadcasting para realizar operaciones sin necesidad de 
bucles. 
4. Comparación con otros métodos: 
○ Analiza cómo se podrían realizar estas tareas sin NumPy y compara 
la eficiencia en términos de código y rendimiento computacional. 

In [1]:
#Importacion de libreria
import numpy as np

In [2]:
# 1. Carga y estructuración de datos
np.random.seed(42)  # Para reproducibilidad
datos = np.random.uniform(100, 200, size=(5, 5))  # Simulamos precios de acciones
datos

array([[137.45401188, 195.07143064, 173.19939418, 159.86584842,
        115.60186404],
       [115.59945203, 105.80836122, 186.61761458, 160.11150117,
        170.80725778],
       [102.05844943, 196.99098522, 183.24426408, 121.23391107,
        118.18249672],
       [118.34045099, 130.4242243 , 152.47564316, 143.19450186,
        129.12291402],
       [161.18528947, 113.94938607, 129.21446485, 136.63618433,
        145.60699842]])

In [3]:
# 2. Análisis y transformación de datos
promedios = datos.mean(axis=1)
maximos = datos.max(axis=1)
minimos = datos.min(axis=1)

# Impresión de resultados
print("Datos simulados (precios de acciones):")
print(np.round(datos, 2), "\n")

print("Promedios por acción:")
print(np.round(promedios, 2))

print(" Máximos por acción:")
print(np.round(maximos, 2))

print(" Mínimos por acción:")
print(np.round(minimos, 2))

Datos simulados (precios de acciones):
[[137.45 195.07 173.2  159.87 115.6 ]
 [115.6  105.81 186.62 160.11 170.81]
 [102.06 196.99 183.24 121.23 118.18]
 [118.34 130.42 152.48 143.19 129.12]
 [161.19 113.95 129.21 136.64 145.61]] 

Promedios por acción:
[156.24 147.79 144.34 134.71 137.32]
 Máximos por acción:
[195.07 186.62 196.99 152.48 161.19]
 Mínimos por acción:
[115.6  105.81 102.06 118.34 113.95]


In [4]:
variacion_porcentual = (datos[:, 1:] - datos[:, :-1]) / datos[:, :-1] * 100
logaritmo = np.log(datos)
exponencial = np.exp(datos / 100)  # Escalado para evitar overflow
normalizado = (datos - datos.min()) / (datos.max() - datos.min())

print("Variación porcentual diaria de cada acción:")
print(variacion_porcentual, "\n")

print("Logaritmo natural de los precios:")
print(logaritmo, "\n")

print("Exponencial de los precios (escalado):")
print(exponencial, "\n")

print("Normalización de los precios (min-max):")
print(normalizado)

Variación porcentual diaria de cada acción:
[[ 41.917597   -11.21232176  -7.69837898 -27.68820534]
 [ -8.46984189  76.37322082 -14.20343597   6.68019257]
 [ 93.01781118  -6.97835037 -33.84026961  -2.51696437]
 [ 10.21102523  16.90745641  -6.08696649  -9.82690513]
 [-29.30534391  13.39636773   5.74372187   6.56547468]] 

Logaritmo natural de los precios:
[[4.9232894  5.2733658  5.1544435  5.07433502 4.75015208]
 [4.75013122 4.66162954 5.22906168 5.07587045 5.14053577]
 [4.62554568 5.28315797 5.21082004 4.79772183 4.77223001]
 [4.77356565 4.8707924  5.02700487 4.96420386 4.86076477]
 [5.08255457 4.73575437 4.86147354 4.9173218  4.9809112 ]] 

Exponencial de los precios (escalado):
[[3.95325828 7.03371001 5.65191226 4.94639231 3.17725825]
 [3.17718162 2.88084488 6.46353347 4.95855819 5.5183151 ]
 [2.77481615 7.1700301  6.24913242 3.36133801 3.26031875]
 [3.26547263 3.68489578 4.59402447 4.18683475 3.63725451]
 [5.0120895  3.12518619 3.64058597 3.92105929 4.28907025]] 

Normalización de lo

In [5]:
# 3. Optimización y selección
rendimiento_dia_3 = datos[:, 2]  # Día 3 de todas las acciones
accion_2_dia_4 = datos[1, 3]     # Acción 2, día 4

print("Rendimiento de todas las acciones en el Día 3:")
print(rendimiento_dia_3, "\n")

print("Valor de la Acción 2 en el Día 4:")
print(accion_2_dia_4)

Rendimiento de todas las acciones en el Día 3:
[173.19939418 186.61761458 183.24426408 152.47564316 129.21446485] 

Valor de la Acción 2 en el Día 4:
160.1115011743209


In [6]:
# Broadcasting: restar el promedio de cada fila (acción)
centrado = datos - datos.mean(axis=1, keepdims=True)

print("Datos originales:")
print(datos, "\n")

print("Promedio por acción (usado para centrar):")
print(promedios, "\n")

print("Datos centrados (restando promedio a cada fila):")
print(centrado)

Datos originales:
[[137.45401188 195.07143064 173.19939418 159.86584842 115.60186404]
 [115.59945203 105.80836122 186.61761458 160.11150117 170.80725778]
 [102.05844943 196.99098522 183.24426408 121.23391107 118.18249672]
 [118.34045099 130.4242243  152.47564316 143.19450186 129.12291402]
 [161.18528947 113.94938607 129.21446485 136.63618433 145.60699842]] 

Promedio por acción (usado para centrar):
[156.23850983 147.78883736 144.3420213  134.71154687 137.31846463] 

Datos centrados (restando promedio a cada fila):
[[-18.78449795  38.83292081  16.96088435   3.62733859 -40.63664579]
 [-32.18938532 -41.98047614  38.82877722  12.32266382  23.01842042]
 [-42.28357187  52.64896391  38.90224278 -23.10811024 -26.15952458]
 [-16.37109588  -4.28732257  17.7640963    8.482955    -5.58863285]
 [ 23.86682484 -23.36907856  -8.10399977  -0.6822803    8.28853379]]


Comparación con métodos tradicionales (sin NumPy)
Sin NumPy:

Habríamos usado listas anidadas y bucles for para calcular promedios, máximos, etc.

Las operaciones serían más largas, menos legibles y más lentas en rendimiento.

Ventajas de NumPy:

Código más limpio, compacto y rápido.

Funciones optimizadas en C para cálculos numéricos.

Posibilidad de manejar matrices grandes con bajo uso de memoria.