Actividad 1

Importa la librería NumPy como np.

Crea una matriz A de 3x3 con números enteros del 1 al 9.

Realiza las siguientes operaciones:
• Suma 10 a cada elemento de la matriz.
• Multiplica la matriz por 2.
• Extrae los elementos mayores a 5 utilizando selección condicional.

Asigna la matriz a una nueva variable B = A y modifica un valor de B. ¿Cambió también A?
Ahora usá B = A.copy() y repetí la modificación. ¿Qué ocurrió con A esta vez?



In [ ]:
import numpy as np

In [4]:
#creacion de matriz 3x3
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])


In [5]:
#Filtro para numeros mayores que 5
mayores_5 = A[A > 5]


In [6]:
mayores_5

array([6, 7, 8, 9])

In [7]:
#Suma 10 a los elementos de la mtriz
A_suma = A + 10
A_suma

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [8]:
#Multiplicacion matriz por 2
A_multi = A * 2
A_multi

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [11]:
#extrae elementos mayores a 5 con una seleccion condicional
A_condicional = A > 5
print (A_condicional)
print("Los elementos que cumplen la condicion son:")
A[A_condicional]

[[False False False]
 [False False  True]
 [ True  True  True]]
Los elementos que cumplen la condicion son:


array([6, 7, 8, 9])

actividad 2

Paso a paso:

Crea un arreglo x con np.arange(1, 17) y redimensionalo en una matriz de 4x4.

Genera un arreglo de 10 elementos equidistantes entre 0 y 100 usando np.linspace().

Crea una matriz aleatoria de 3x3 con enteros entre 1 y 20 usando np.random.randint().

Aplica np.sqrt() y np.log() sobre las matrices creadas (cuando sea posible).

¿Qué diferencias notás en la forma de aplicar funciones sobre arreglos enteros vs flotantes?



In [6]:
# Arreglo del 1 al 16
x = np.arange(1, 17)

# Convertirlo en matriz 4x4
matriz_4x4 = x.reshape((4, 4))

print("Matriz 4x4:\n", matriz_4x4)

Matriz 4x4:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [8]:
lineal = np.linspace(0, 100, 10)
print("Arreglo equidistante:\n", lineal)

Arreglo equidistante:
 [  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]


In [9]:
aleatoria = np.random.randint(1, 21, size=(3, 3))
print("Matriz aleatoria 3x3:\n", aleatoria)


Matriz aleatoria 3x3:
 [[19 20  9]
 [10 17 16]
 [15  8 13]]


In [10]:
# Raíz cuadrada
raiz = np.sqrt(aleatoria)
print("Raíz cuadrada:\n", raiz)

# Logaritmo natural
logaritmo = np.log(aleatoria)
print("Logaritmo natural:\n", logaritmo)


Raíz cuadrada:
 [[4.35889894 4.47213595 3.        ]
 [3.16227766 4.12310563 4.        ]
 [3.87298335 2.82842712 3.60555128]]
Logaritmo natural:
 [[2.94443898 2.99573227 2.19722458]
 [2.30258509 2.83321334 2.77258872]
 [2.7080502  2.07944154 2.56494936]]


Nota
Cuando aplicas funciones como np.sqrt() o np.log() a arreglos enteros, NumPy devuelve un nuevo arreglo con valores flotantes, ya que las operaciones pueden resultar en decimales. Por otro lado, np.linspace() ya genera valores flotantes, por lo tanto, no se necesita conversión de tipo.

